### ISSUE TITLE
[UPDATE]Update Star Command Documentation

### ISSUE THREAD

**Issue by LandonLloyd** [nhcarrigan/Becca-Lyria-documentation#97]
## Description
Since the Star command has been updated for the bot the documentation site should better reflect what the bot does now. It should say something like - This command sends a message embed to the channel it was sent in. The embed contains the command author's name, the [reason] if provided, and a shiny gold star!

## Related Pull Request

https://github.com/nhcarrigan/Becca-Lyria/pull/442

**Comment by LandonLloyd** [comment]
I would do it I just don't know the file structure and stuff on how Angular.js works. Thanks @nhcarrigan!

**Comment by nhcarrigan** [comment]
In this case, it would take updating the description within the command data object:

https://github.com/nhcarrigan/Becca-Lyria-documentation/blob/main/src/assets/data/manual.ts#L316-L321
